services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/gabrielsdl_development
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  bundle:
  postgres-data:
